package audit_test

// The gate on docs/character.schema.json: that it admits every record the
// engine writes, that it refuses records the engine could not have
// written, and that the checker enforcing it is not vacuous.

import (
	"encoding/json"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"testing"

	"github.com/philoserf/t5chargen/chargen"
)

// schemaPath is the contract docs/PRD.md's JSON conventions require:
// "Full schema (with minimal and complete examples) lives in the tool
// repo, versioned by schema_version".
const (
	schemaPath      = docsPath + "character.schema.json"
	minimalExample  = docsPath + "character.minimal.json"
	completeExample = docsPath + "character.complete.json"
)

// TestEveryFixtureValidates verifies the schema describes what the engine
// actually writes. The fixtures are its output, byte for byte, across all
// thirteen careers and both deciders.
func TestEveryFixtureValidates(t *testing.T) {
	records, err := filepath.Glob(filepath.Join("..", "chargen", "testdata", "*.json"))
	if err != nil {
		t.Fatal(err)
	}

	if len(records) == 0 {
		t.Fatal("no fixtures found; this gate would be asserting nothing")
	}

	for _, record := range records {
		t.Run(filepath.Base(record), func(t *testing.T) {
			problems, err := validate(schemaPath, record)
			if err != nil {
				t.Fatal(err)
			}

			for _, problem := range problems {
				t.Error(problem)
			}
		})
	}
}

// TestExamplesValidate verifies the two examples the PRD asks the schema to
// ship with. The minimal one is the smallest record the schema admits; the
// complete one is a real generated record rather than a fabricated maximum,
// which is why the coverage of the schema's properties is checked
// separately rather than assumed of it.
func TestExamplesValidate(t *testing.T) {
	for _, example := range []string{minimalExample, completeExample} {
		t.Run(example, func(t *testing.T) {
			problems, err := validate(schemaPath, example)
			if err != nil {
				t.Fatal(err)
			}

			for _, problem := range problems {
				t.Error(problem)
			}
		})
	}
}

// completeExample is the fixture docs/character.complete.json is a copy
// of. The example has to be a record the engine really wrote, and the only
// way to keep it one is to say which.
const completeFixture = "career_scout.json"

// TestTheExamplesTrackTheEngine keeps the two shipped examples honest.
//
// The complete one is a copy of a golden fixture, and `task goldens`
// rewrites the fixture without touching the copy — a drifted copy would go
// on validating, so nothing else here would notice. The provenance strings
// are pinned the same way: an example advertising a schema_version the
// engine no longer stamps documents a contract that has moved.
func TestTheExamplesTrackTheEngine(t *testing.T) {
	fixture := filepath.Join("..", "chargen", "testdata", completeFixture)

	if canonical(t, completeExample) != canonical(t, fixture) {
		t.Errorf("the complete example is no longer %s; re-copy it, because task goldens does not", fixture)
	}

	// policy_version is deliberately absent: a record generated by
	// something other than the auto policy carries "none" (chargen's
	// provenance header), so it is not a constant the examples track.
	stamped := map[string]string{
		"schema_version": chargen.SchemaVersion,
		"ruleset":        chargen.Ruleset,
		"engine_version": chargen.EngineVersion,
	}

	for _, example := range []string{minimalExample, completeExample} {
		record := readRecord(t, example)

		for field, want := range stamped {
			if got, _ := record[field].(string); got != want {
				t.Errorf("%s carries %s %q; the engine stamps %q", example, field, got, want)
			}
		}
	}
}

// canonical re-encodes a JSON file with its keys sorted, so two files that
// differ only in whitespace compare equal. docs/*.json is prettier's and
// chargen/testdata/*.json is json.MarshalIndent's, so the two copies of
// the complete example are never byte-identical.
func canonical(t *testing.T, path string) string {
	t.Helper()

	data, err := os.ReadFile(filepath.Clean(path))
	if err != nil {
		t.Fatal(err)
	}

	var doc any
	if err := json.Unmarshal(data, &doc); err != nil {
		t.Fatal(err)
	}

	encoded, err := json.Marshal(doc)
	if err != nil {
		t.Fatal(err)
	}

	return string(encoded)
}

// TestAnUnresolvableRefIsRefused is the mutation test for the load-time
// check that every $ref names something. Without it a renamed $def would
// delete every rule beneath the ref and leave every other test here
// passing.
func TestAnUnresolvableRefIsRefused(t *testing.T) {
	data, err := os.ReadFile(filepath.Clean(schemaPath))
	if err != nil {
		t.Fatal(err)
	}

	broken := strings.Replace(string(data), `"#/$defs/rng"`, `"#/$defs/rgn"`, 1)
	if broken == string(data) {
		t.Fatal("the schema no longer refers to #/$defs/rng; this gate would be asserting nothing")
	}

	if _, err := newChecker([]byte(broken)); err == nil {
		t.Error("a schema referring to a $def it does not define was accepted")
	}
}

// TestAKeywordBesideARefStillApplies is the mutation test for the other
// half of $ref handling: draft 2020-12 applies the keywords written next
// to a $ref as well, and a checker that let the ref replace its siblings
// would silently drop every rule beside one.
func TestAKeywordBesideARefStillApplies(t *testing.T) {
	data, err := os.ReadFile(filepath.Clean(schemaPath))
	if err != nil {
		t.Fatal(err)
	}

	var schema map[string]any
	if err := json.Unmarshal(data, &schema); err != nil {
		t.Fatal(err)
	}

	defs, _ := schema["$defs"].(map[string]any)
	character, _ := defs["character"].(map[string]any)
	properties, _ := character["properties"].(map[string]any)

	rng, _ := properties["rng"].(map[string]any)
	if _, ok := rng["$ref"]; !ok {
		t.Fatal("the character's rng is no longer a $ref; this gate would be asserting nothing")
	}

	rng["required"] = []any{"nonesuch"}

	doctored, err := json.Marshal(schema)
	if err != nil {
		t.Fatal(err)
	}

	c, err := newChecker(doctored)
	if err != nil {
		t.Fatal(err)
	}

	if problems := c.check(c.root, readRecord(t, minimalExample), "record"); len(problems) == 0 {
		t.Error("a rule written beside a $ref was not applied")
	}
}

// brokenRecords are the ways a record can be wrong that the schema claims
// to catch. Each is the minimal example with one thing done to it, and
// each must fail — for a reason naming what was done.
//
// This is the list that makes the gate mean something. A checker that
// silently passed everything would satisfy every other test in this file.
var brokenRecords = map[string]struct {
	blame  string
	damage func(map[string]any)
}{
	"a required field is missing": {
		blame:  "upp is required",
		damage: func(r map[string]any) { delete(r, "upp") },
	},
	"an unknown field is present": {
		blame:  "not a property",
		damage: func(r map[string]any) { r["favourite_colour"] = "blue" },
	},
	"a string where an integer belongs": {
		blame:  "want integer",
		damage: func(r map[string]any) { r["age"] = "thirty" },
	},
	"a fractional integer": {
		blame:  "want integer",
		damage: func(r map[string]any) { r["age"] = 30.5 },
	},
	"a negative seed": {
		blame:  "at least",
		damage: func(r map[string]any) { nested(r, "rng")["seed"] = -1.0 },
	},
	"an event kind outside the vocabulary": {
		blame:  "is not one of",
		damage: func(r map[string]any) { firstEvent(r)["kind"] = "rumination" },
	},
	"an event carrying the wrong payload": {
		blame: "forbids",
		damage: func(r map[string]any) {
			firstEvent(r)["throw"] = map[string]any{
				"expr": "2D", "dice": []any{1.0, 2.0}, "total": 3.0, "cite": "somewhere",
			}
		},
	},
	"an event carrying no payload at all": {
		blame:  "required and absent",
		damage: func(r map[string]any) { delete(firstEvent(r), "step") },
	},
	"a nested required field is missing": {
		blame:  "algorithm is required",
		damage: func(r map[string]any) { delete(nested(r, "rng"), "algorithm") },
	},
	"a nested unknown field": {
		blame:  "not a property",
		damage: func(r map[string]any) { nested(r, "characteristics")["luck"] = 12.0 },
	},
}

// nested reaches into an object property, which every damage function
// knows is there because the minimal example carries it.
func nested(record map[string]any, name string) map[string]any {
	object, _ := record[name].(map[string]any)

	return object
}

// firstEvent reaches the record's first event.
func firstEvent(record map[string]any) map[string]any {
	events, _ := record["events"].([]any)
	if len(events) == 0 {
		return map[string]any{}
	}

	event, _ := events[0].(map[string]any)

	return event
}

// TestTheCheckerCatchesWhatItClaimsTo runs the broken records. Each must
// be refused, and refused for the stated reason rather than incidentally.
func TestTheCheckerCatchesWhatItClaimsTo(t *testing.T) {
	for name, tc := range brokenRecords {
		t.Run(name, func(t *testing.T) {
			record := readRecord(t, minimalExample)
			tc.damage(record)

			problems := checkRecord(t, record)
			if len(problems) == 0 {
				t.Fatalf("%s was accepted; the schema claims to refuse it", name)
			}

			if !strings.Contains(strings.Join(problems, "\n"), tc.blame) {
				t.Errorf("refused for the wrong reason.\nwant a problem mentioning %q\ngot:\n  %s",
					tc.blame, strings.Join(problems, "\n  "))
			}
		})
	}
}

// TestTheMinimalExampleIsMinimal verifies the minimal example earns its
// name: removing any one of its top-level fields must break it. A minimal
// example carrying something optional would misdocument what a record
// needs.
func TestTheMinimalExampleIsMinimal(t *testing.T) {
	base := readRecord(t, minimalExample)

	for field := range base {
		record := readRecord(t, minimalExample)
		delete(record, field)

		if problems := checkRecord(t, record); len(problems) == 0 {
			t.Errorf("the minimal example still validates without %q, so %q is not required", field, field)
		}
	}
}

// readRecord loads a record as a plain document.
func readRecord(t *testing.T, path string) map[string]any {
	t.Helper()

	data, err := os.ReadFile(filepath.Clean(path))
	if err != nil {
		t.Fatal(err)
	}

	var record map[string]any
	if err := json.Unmarshal(data, &record); err != nil {
		t.Fatal(err)
	}

	return record
}

// checkRecord validates an in-memory record.
//
// The record goes back through JSON first. A damaged record is built with
// Go values, and Go has integers where parsed JSON has only float64 — so a
// case written as -1 would reach the checker as a type it can never meet
// in a file, and be refused for the wrong reason. Round-tripping puts the
// damage in the value space the checker actually validates.
func checkRecord(t *testing.T, record map[string]any) []string {
	t.Helper()

	encoded, err := json.Marshal(record)
	if err != nil {
		t.Fatal(err)
	}

	var parsed any
	if err := json.Unmarshal(encoded, &parsed); err != nil {
		t.Fatal(err)
	}

	data, err := os.ReadFile(filepath.Clean(schemaPath))
	if err != nil {
		t.Fatal(err)
	}

	c, err := newChecker(data)
	if err != nil {
		t.Fatal(err)
	}

	return c.check(c.root, parsed, "record")
}

// TestEverySchemaPropertyIsExercised is the dead-data gate applied to the
// schema. A property nothing ever produces is either a field the engine no
// longer writes or a shape nobody has checked, and both are worth knowing
// about; the schema is a claim about real records, not a wish list.
//
// The complete example is a real generated record rather than a fabricated
// maximum, so it does not reach every optional field on its own. What is
// unreached is listed here with a reason, the same bargain the chart-data
// gate strikes.
func TestEverySchemaPropertyIsExercised(t *testing.T) {
	records, err := filepath.Glob(filepath.Join("..", "chargen", "testdata", "*.json"))
	if err != nil {
		t.Fatal(err)
	}

	if len(records) == 0 {
		t.Fatal("no fixtures found; this gate would be asserting nothing")
	}

	seen := keysAcross(t, append(records, minimalExample, completeExample))

	for _, property := range schemaProperties(t) {
		if seen[property] || unexercised[property] != "" {
			continue
		}

		t.Errorf("the schema describes %q and no fixture or example carries it; "+
			"produce one, or say why not in unexercised", property)
	}

	for property, why := range unexercised {
		if seen[property] {
			t.Errorf("%q is exercised now (%s); remove it from unexercised", property, why)
		}
	}
}

// unexercised are schema properties no fixture or example carries, and
// why. Every entry is a rule the engine implements down a path the pinned
// seeds do not reach — not a field that does nothing.
var unexercised = map[string]string{
	"errata": "the applied ERRATA.md deviations; no rule records one against a character yet, " +
		"so the list is always absent",
	"deep_space":       "chart B's cell 6 6 (I-97); no fixture rolls its homeworld, and none is assigned deep space",
	"rolled_homeworld": "--homeworld random; every fixture takes the assigned world, so the input is false and omitted",
	"homeworld_assigned": "--homeworld; no fixture names one, so step B offers chart B's list " +
		"and the input is false and omitted",
	"service":      "the Service Academy's service; the auto policy never selects the Academy (POLICY.md)",
	"exiled":       "chart 11's Noble exile; the pinned Noble seed is not exiled",
	"prison_years": "a Rogue serving a sentence; the pinned Rogue seed serves none",
}

// keysAcross gathers every property name appearing anywhere in any of the
// documents.
func keysAcross(t *testing.T, paths []string) map[string]bool {
	t.Helper()

	seen := map[string]bool{}

	for _, path := range paths {
		data, err := os.ReadFile(filepath.Clean(path))
		if err != nil {
			t.Fatal(err)
		}

		var doc any
		if err := json.Unmarshal(data, &doc); err != nil {
			t.Fatal(err)
		}

		collectKeys(doc, seen)
	}

	return seen
}

// collectKeys gathers every property name appearing anywhere in a document.
func collectKeys(doc any, seen map[string]bool) {
	switch value := doc.(type) {
	case map[string]any:
		for key, child := range value {
			seen[key] = true

			collectKeys(child, seen)
		}
	case []any:
		for _, child := range value {
			collectKeys(child, seen)
		}
	}
}

// schemaProperties lists every property name the schema describes.
func schemaProperties(t *testing.T) []string {
	t.Helper()

	data, err := os.ReadFile(filepath.Clean(schemaPath))
	if err != nil {
		t.Fatal(err)
	}

	var schema map[string]any
	if err := json.Unmarshal(data, &schema); err != nil {
		t.Fatal(err)
	}

	seen := map[string]bool{}
	defs, _ := schema["$defs"].(map[string]any)

	for _, def := range defs {
		object, _ := def.(map[string]any)

		properties, _ := object["properties"].(map[string]any)
		for name := range properties {
			seen[name] = true
		}
	}

	names := make([]string, 0, len(seen))
	for name := range seen {
		names = append(names, name)
	}

	sort.Strings(names)

	return names
}

// consequenceFields is what each consequence kind is ever seen to carry,
// beyond the kind and cause every one of them has.
//
// Observed and pinned, not derived from the rules: it is a golden, and a
// change to it is a change to read rather than to wave through. It exists
// because the schema leaves all seven payload fields optional — which
// field a consequence carries turns on its kind, and fifty-five if/then
// branches in the schema would be a second copy of the code.
//
// The sets are unions rather than exact shapes. Payload fields are
// omitempty, so a zero value simply is not written: characteristic_change
// carries "value" where the resulting value is non-zero and drops it where
// it is not. An earlier version of this gate asserted that a kind carries
// the same fields every time, and the fixtures disproved it in eleven
// places within a second of running.
var consequenceFields = map[string]string{
	"aging_effect":          "characteristic delta value",
	"associated":            "career skill",
	"benefit":               "career delta skill value",
	"benefit_lost":          "",
	"birthdate":             "detail value",
	"branch_set":            "career skill",
	"career_changed":        "career",
	"career_ended":          "career",
	"disabled":              "characteristic",
	"characteristic_change": "characteristic delta value",
	// No value: the floor is zero and Value is omitempty, so the event
	// carries what was refused and the floor is implied by the kind.
	"characteristic_floored":  "characteristic delta",
	"characteristic_reset":    "characteristic delta value",
	"characteristic_set":      "characteristic value",
	"comeback":                "value",
	"commendation":            "career delta skill value",
	"dead":                    "characteristic value",
	"discovery":               "value",
	"elevated":                "career",
	"entitlement":             "delta skill value",
	"exiled":                  "career value",
	"extremely_major_illness": "value",
	"fame_change":             "delta value",
	"fame_computed":           "mods skill value",
	"hobby_set":               "skill",
	"intrigue":                "career value",
	"job_set":                 "skill",
	"land_grant":              "career value",
	"major_illness":           "value",
	"major_set":               "skill",
	"mandatory_continue":      "",
	"masterpiece":             "career delta value",
	"medal":                   "career skill value",
	"minor_set":               "skill",
	"no_award":                "career skill value",
	"operation":               "career skill value",
	"payoff":                  "career delta skill value",
	"publication":             "delta value",
	"rank_set":                "career skill",
	"reserve":                 "career skill",
	"returned_from_exile":     "career",
	"sanity_mod":              "career delta",
	"scheme":                  "career skill value",
	"service_badge":           "career value",
	"ship_shares":             "delta value",
	"skill_awarded":           "delta skill value",
	"specialty_set":           "career skill",
	"talent_set":              "value",
	"tenure":                  "career",
	"undercover_assignment":   "career skill",
	"wound_badge":             "value",
	"years_elapsed":           "value",
}

// TestEachConsequenceKindKeepsItsShape verifies the claim the schema makes
// about consequences: their payload turns on the kind, and the rule is
// pinned here rather than in the schema.
func TestEachConsequenceKindKeepsItsShape(t *testing.T) {
	records, err := filepath.Glob(filepath.Join("..", "chargen", "testdata", "*.json"))
	if err != nil {
		t.Fatal(err)
	}

	// The same premise its two siblings state: with no fixtures the loop
	// below reports every pinned kind as unemitted, so the gate fails
	// either way — but with fifty-odd errors about missing consequences
	// instead of one naming the cause.
	if len(records) == 0 {
		t.Fatal("no fixtures found; this gate would be asserting nothing")
	}

	seen := map[string]bool{}

	for _, path := range records {
		for kind, fields := range consequenceShapes(t, path) {
			seen[kind] = true

			want, known := consequenceFields[kind]
			if !known {
				t.Errorf("consequence %q is new (%s in %s); add it to consequenceFields",
					kind, fields, filepath.Base(path))

				continue
			}

			for field := range strings.FieldsSeq(fields) {
				if !strings.Contains(" "+want+" ", " "+field+" ") {
					t.Errorf("consequence %q carries %q in %s, which it was not pinned to carry",
						kind, field, filepath.Base(path))
				}
			}
		}
	}

	for kind := range consequenceFields {
		if !seen[kind] {
			t.Errorf("consequence %q is pinned and no fixture emits it; remove it or produce one",
				kind)
		}
	}
}

// consequenceShapes reports the payload fields each consequence kind
// carries in one record, space-separated and sorted.
//
// The union across the record's events, not the last one's shape: payload
// fields are omitempty, so the same kind is written with different fields
// at different points in a run, and reading only the last occurrence would
// leave every earlier one unchecked.
func consequenceShapes(t *testing.T, path string) map[string]string {
	t.Helper()

	data, err := os.ReadFile(filepath.Clean(path))
	if err != nil {
		t.Fatal(err)
	}

	var record struct {
		Events []struct {
			Kind        string         `json:"kind"`
			Consequence map[string]any `json:"consequence"`
		} `json:"events"`
	}

	if err := json.Unmarshal(data, &record); err != nil {
		t.Fatal(err)
	}

	carried := map[string]map[string]bool{}

	for _, event := range record.Events {
		if event.Kind != "consequence" {
			continue
		}

		kind, _ := event.Consequence["kind"].(string)

		if carried[kind] == nil {
			carried[kind] = map[string]bool{}
		}

		for name := range event.Consequence {
			if name != "kind" && name != "cause" {
				carried[kind][name] = true
			}
		}
	}

	return joinFields(carried)
}

// joinFields renders each kind's field set the way consequenceFields
// writes one: sorted and space-separated.
func joinFields(carried map[string]map[string]bool) map[string]string {
	shapes := map[string]string{}

	for kind, names := range carried {
		fields := make([]string, 0, len(names))
		for name := range names {
			fields = append(fields, name)
		}

		sort.Strings(fields)
		shapes[kind] = strings.Join(fields, " ")
	}

	return shapes
}

// unemittedKinds are consequence kinds the engine declares and no pinned
// seed produces, and why. Each is a path the rules reach and the fourteen
// fixtures do not — a real outcome rather than a kind that does nothing.
var unemittedKinds = map[string]string{
	"career_not_begun": "a failed To Begin; every fixture's character enters his career",
	// Both left the fixtures at policy 0.20.0: the Rogue golden's seed
	// now spends a term at school, and the scheme that used to end in a
	// sentence is a term later than the run reaches. The path is not lost
	// — TestRoguePrisonTermTakesOnlyPrisonSkills pins it on its own seed,
	// with schooling declined — only its appearance in a golden record.
	"imprisoned":       "a Rogue's prison term; covered by TestRoguePrisonTermTakesOnlyPrisonSkills",
	"job_undetermined": "chart 04's Job left undetermined; no fixture's Citizen reaches it",
	"sentenced":        "a Rogue's sentence; covered by TestRoguePrisonTermTakesOnlyPrisonSkills",
	"waived":           "a waiver that succeeded; the auto policy's waivers all fail on these seeds",
}

// TestEveryConsequenceKindIsAccountedFor verifies the schema's vocabulary
// against what the engine can actually emit. A kind in the enum that
// nothing produces is either a rule nobody exercises or one that has
// quietly stopped working, and the difference is worth writing down.
func TestEveryConsequenceKindIsAccountedFor(t *testing.T) {
	declared := scan(t, isGoSource, regexp.MustCompile(`ConsequenceKind = "([a-z_0-9]+)"`))
	if len(declared) == 0 {
		t.Fatal("no consequence kinds found; this gate would be asserting nothing")
	}

	for _, kind := range declared {
		_, emitted := consequenceFields[kind]
		if emitted == (unemittedKinds[kind] != "") {
			if emitted {
				t.Errorf("%q is emitted by a fixture; remove it from unemittedKinds", kind)
			} else {
				t.Errorf("%q is declared and no fixture emits it; produce one, or say why not in unemittedKinds", kind)
			}
		}
	}

	assertVocabulary(t, "consequenceEvent", "kind", declared)
}

// vocabularies are the schema's closed lists and the Go constants each one
// transcribes. A value the engine can write and the schema does not hold
// makes the schema wrong about a real record, and nothing else here would
// notice until some fixture happened to carry it.
// The package each is declared in matters: "Kind" is a type name three
// packages use, so a pattern loose enough to find benefit.Kind finds
// skill.Kind as well and reports five vocabulary values that belong to
// another list entirely.
var vocabularies = []struct {
	def, property, dir, pattern string
}{
	{def: "consequenceEvent", property: "kind", dir: "chargen", pattern: `ConsequenceKind = "([a-z_0-9]+)"`},
	{def: "event", property: "kind", dir: "chargen", pattern: `EventKind\s+= "([a-z]+)"`},
	{def: "choiceEvent", property: "decider", dir: "chargen", pattern: `DeciderKind = "([a-z]+)"`},
	{def: "benefitRecord", property: "kind", dir: "benefit", pattern: `\bKind = "([a-z_]+)"`},
}

// TestEverySchemaVocabularyMatchesTheEngine checks each closed list in the
// schema against the constants it transcribes, in both directions.
//
// The consequence kinds had this and the other three did not, which meant a
// new benefit kind would have gone unnoticed until a fixture happened to
// carry one — and the fixtures reach six of the nineteen.
func TestEverySchemaVocabularyMatchesTheEngine(t *testing.T) {
	for _, v := range vocabularies {
		t.Run(v.def+"."+v.property, func(t *testing.T) {
			declared := scan(t, inPackage(v.dir), regexp.MustCompile(v.pattern))
			if len(declared) == 0 {
				t.Fatalf("no constants matched %s; this gate would be asserting nothing", v.pattern)
			}

			assertVocabulary(t, v.def, v.property, declared)
		})
	}
}

// assertVocabulary compares one schema enum with the constants behind it.
func assertVocabulary(t *testing.T, def, property string, declared []string) {
	t.Helper()

	inSchema := map[string]bool{}
	for _, value := range schemaEnum(t, def, property) {
		inSchema[value] = true
	}

	inGo := map[string]bool{}

	for _, value := range declared {
		inGo[value] = true

		if !inSchema[value] {
			t.Errorf("the engine writes %q and %s.%s does not hold it", value, def, property)
		}
	}

	for value := range inSchema {
		if !inGo[value] {
			t.Errorf("%s.%s holds %q and no constant declares it", def, property, value)
		}
	}
}

// inPackage keeps one package's own source, excluding tests.
func inPackage(dir string) func(string) bool {
	return func(path string) bool {
		return strings.Contains(path, "/"+dir+"/") && isGoSource(path)
	}
}

// isGoSource keeps the engine's own source, excluding tests.
func isGoSource(path string) bool {
	return strings.HasSuffix(path, ".go") && !strings.HasSuffix(path, "_test.go")
}

// schemaEnum reads one property's enum out of the schema.
func schemaEnum(t *testing.T, def, property string) []string {
	t.Helper()

	data, err := os.ReadFile(filepath.Clean(schemaPath))
	if err != nil {
		t.Fatal(err)
	}

	var schema struct {
		Defs map[string]struct {
			Properties map[string]struct {
				Enum []string `json:"enum"`
			} `json:"properties"`
		} `json:"$defs"`
	}

	if err := json.Unmarshal(data, &schema); err != nil {
		t.Fatal(err)
	}

	return schema.Defs[def].Properties[property].Enum
}

// TestAWholeNumberSatisfiesTypeNumber pins the one place JSON Schema's
// type names are not disjoint: every integer is a number, so a property
// declared "number" must accept 5 as readily as 5.5.
//
// Constructed rather than drawn from the record, and deliberately so.
// character.schema.json declares no "number" today, so nothing exercises
// this and no fixture would notice if it broke. The first fractional
// field added to the record — a rate, a multiplier — gets "number", and a
// checker without this rule then fails every record whose value happened
// to land whole, reading as a schema bug rather than a checker one.
func TestAWholeNumberSatisfiesTypeNumber(t *testing.T) {
	c, err := newChecker([]byte(`{"type": "object", "properties": {"rate": {"type": "number"}}}`))
	if err != nil {
		t.Fatal(err)
	}

	for _, value := range []any{5.0, 5.5, -2.0} {
		if problems := c.check(c.root, map[string]any{"rate": value}, "record"); len(problems) != 0 {
			t.Errorf("rate %v refused under type number: %s", value, strings.Join(problems, "; "))
		}
	}

	// The reverse still fails: a fractional value is not an integer.
	c, err = newChecker([]byte(`{"type": "object", "properties": {"terms": {"type": "integer"}}}`))
	if err != nil {
		t.Fatal(err)
	}

	if problems := c.check(c.root, map[string]any{"terms": 2.5}, "record"); len(problems) == 0 {
		t.Error("terms 2.5 was accepted under type integer")
	}
}

// TestANonScalarConstIsCompared pins that the checker reports a mismatch
// on an array or object const rather than crashing.
//
// Go's == on two any values panics when the dynamic type is uncomparable,
// and a JSON array parses to []any. Every const in character.schema.json
// is a string, so nothing exercises this and no fixture would notice if it
// regressed — but the crash takes the whole test binary with it, which
// reads as a broken build rather than a checker bug.
func TestANonScalarConstIsCompared(t *testing.T) {
	c, err := newChecker([]byte(`{"type": "object", "properties": {"pair": {"const": [1, 2]}}}`))
	if err != nil {
		t.Fatal(err)
	}

	if problems := c.check(c.root, map[string]any{"pair": []any{1.0, 2.0}}, "record"); len(problems) != 0 {
		t.Errorf("the matching array was refused: %s", strings.Join(problems, "; "))
	}

	if problems := c.check(c.root, map[string]any{"pair": []any{1.0, 3.0}}, "record"); len(problems) == 0 {
		t.Error("a different array was accepted under const [1, 2]")
	}
}
