package chargen

import (
	"github.com/philoserf/t5chargen/dice"
	"github.com/philoserf/t5chargen/ehex"
)

// Characteristics are the six standard human characteristics (docs/PRD.md
// FR1). "Humans have the six standard characteristics: Strength, Dexterity,
// Endurance, Intelligence, Education, and Social Standing." (Book 1 p. 123)
//
// Values are stored numeric; the UPP hex string is derived (docs/PRD.md,
// JSON conventions).
type Characteristics struct {
	Str int `json:"str"`
	Dex int `json:"dex"`
	End int `json:"end"`
	Int int `json:"int"`
	Edu int `json:"edu"`
	Soc int `json:"soc"`
}

// UPP renders the six-character Universal Personality Profile: "The
// Characteristics for each Character are shown in the convenient six-digit
// UPP Universal Personality Profile" (p. 48), in the order Str Dex End Int
// Edu Soc ("the UPP Human format SDEIES", p. 22), each digit in eHex.
//
// A value outside the eHex range renders as "?" — p. 22 shows the unknown
// value convention as 77??67.
func (c *Characteristics) UPP() string {
	upp := make([]byte, 0, 6)

	for _, value := range []int{c.Str, c.Dex, c.End, c.Int, c.Edu, c.Soc} {
		digit, err := ehex.Encode(value)
		if err != nil {
			digit = '?'
		}

		upp = append(upp, digit)
	}

	return string(upp)
}

// Value returns the named characteristic's value; ok is false for a name
// outside the six standard abbreviations (p. 48: "A Characteristic can be
// abbreviated with its first three letters").
func (c *Characteristics) Value(name string) (int, bool) {
	field := c.field(name)
	if field == nil {
		return 0, false
	}

	return *field, true
}

// Add applies a delta to the named characteristic, reporting the new value;
// ok is false for an unknown name.
func (c *Characteristics) Add(name string, delta int) (int, bool) {
	field := c.field(name)
	if field == nil {
		return 0, false
	}

	*field += delta

	return *field, true
}

// field maps a standard abbreviation to its field.
func (c *Characteristics) field(name string) *int {
	switch name {
	case "Str":
		return &c.Str
	case "Dex":
		return &c.Dex
	case "End":
		return &c.End
	case "Int":
		return &c.Int
	case "Edu":
		return &c.Edu
	case "Soc":
		return &c.Soc
	}

	return nil
}

// RollCharacteristics rolls the six standard human characteristics, emitting
// a throw and a consequence event for each.
//
// "Assume the character is Human with standard characteristics generated by
// 2D each. ... Roll two dice six times and record the results in the order
// they are rolled: Strength, Dexterity, Endurance, Intelligence, Education,
// and Social Standing. Defer rolling for Psi and Sanity until later; knowing
// these values are not necessary at this point." (chart A, p. 56)
//
// The roll order above is stream order and part of the replay contract.
// Psi and Sanity are never rolled: chart A defers them and v1 excludes
// psionics (docs/PRD.md non-goals); rolling them would consume stream faces
// and shift every subsequent throw.
func RollCharacteristics(roller *dice.Roller, log *Log) Characteristics {
	const cite = "Book 1 p. 56 chart A"

	var c Characteristics

	for _, characteristic := range []struct {
		name string
		dst  *int
	}{
		{"Str", &c.Str},
		{"Dex", &c.Dex},
		{"End", &c.End},
		{"Int", &c.Int},
		{"Edu", &c.Edu},
		{"Soc", &c.Soc},
	} {
		roll := roller.Roll(2)
		*characteristic.dst = roll.Total

		cause := log.Roll(roll, cite)
		log.Consequence(ConsequenceEvent{
			Cause:          cause,
			Kind:           ConsequenceCharacteristicSet,
			Characteristic: characteristic.name,
			Value:          roll.Total,
		})
	}

	return c
}
