package chargen

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"maps"
	"slices"
)

// The replay failures, separated because they mean different things to a
// reader. A provenance mismatch says the record and this binary are not
// comparable at all; a divergence says they are, and disagreed.
var (
	// ErrReplayProvenance reports a record this build cannot re-run:
	// a different engine, ruleset, or random algorithm. Replay stops
	// before rolling anything, because every later complaint would be a
	// consequence of this one.
	ErrReplayProvenance = errors.New("record was not produced by this engine")

	// ErrReplayDiverged reports a record this build re-ran and did not
	// reproduce. The message names the sequence number of the first
	// disagreeing event (docs/PRD.md, Replay and provenance contract).
	ErrReplayDiverged = errors.New("replay diverged from the record")
)

// Replay re-runs the generation the record describes and verifies that it
// reproduces the record exactly.
//
// Per docs/PRD.md's replay contract, the run is driven "from the recorded
// seed and choice events": the choice events are input, reapplied through
// the Decider seam, and everything else in the log — steps, throws,
// consequences — is verification data recomputed from scratch. It returns
// the regenerated character so a caller can diff it.
//
// policy_version is deliberately not part of the provenance check. Replay
// reapplies recorded choices and never consults the policy, so a record
// made under one POLICY.md version verifies under any other — which is
// also why the fixtures carrying "none" (generated by test deciders rather
// than the policy) are replayable at all.
func Replay(stored Character) (Character, error) {
	if err := checkProvenance(stored); err != nil {
		return Character{}, err
	}

	decider := &replayDecider{}

	for _, event := range stored.Events {
		if event.Kind == EventChoice && event.Choice != nil {
			decider.choices = append(decider.choices, recordedChoice{seq: event.Seq, event: *event.Choice})
		}
	}

	replayed, err := Generate(Options{
		Seed:          stored.RNG.Seed,
		Name:          stored.Name,
		Career:        stored.Inputs.Career,
		Homeworld:     stored.Homeworld,
		CurrentYear:   stored.Inputs.CurrentYear,
		RollHomeworld: stored.Inputs.RolledHomeworld,
		Decider:       decider,
	})
	if err != nil {
		return Character{}, fmt.Errorf("re-running the record: %w", err)
	}

	if err := compareEvents(stored.Events, replayed.Events); err != nil {
		return replayed, err
	}

	// The event logs agreeing is not the whole contract: "Derived values
	// are stored and recomputed on replay" (docs/PRD.md, JSON
	// conventions), and no event carries the final credits, skill list or
	// Fame. Comparing the marshalled records catches a derived value that
	// drifted while every event that fed it stayed put.
	if err := compareRecords(stored, replayed); err != nil {
		return replayed, err
	}

	return replayed, nil
}

// checkProvenance rejects a record this build cannot meaningfully re-run.
// Reporting it here rather than letting the run diverge matters: a record
// from another engine would fail at some arbitrary sequence number, and
// that number would describe nothing.
func checkProvenance(stored Character) error {
	for _, field := range []struct {
		name, got, want string
	}{
		{"schema_version", stored.SchemaVersion, SchemaVersion},
		{"engine_version", stored.EngineVersion, EngineVersion},
		{"ruleset", stored.Ruleset, Ruleset},
		{"rng.algorithm", stored.RNG.Algorithm, RNGAlgorithm},
	} {
		if field.got != field.want {
			return fmt.Errorf("%w: %s is %q, this build is %q",
				ErrReplayProvenance, field.name, field.got, field.want)
		}
	}

	return nil
}

// compareEvents is the verifier proper: it reports the first event that
// disagrees, by sequence number, and it is what actually catches a
// divergence. The checks inside replayDecider.Choose are fail-fast
// diagnostics layered on top — anything they catch reaches the event log
// too, and would be reported here, but later and less legibly.
//
// It also subsumes a count check on the choices: a re-run that consumed
// fewer recorded choices than the record holds has fewer choice events, so
// the missing one is reported here.
//
// The contract: "exits non-zero at the first mismatch, reporting the diverging
// event's sequence number" (docs/PRD.md, Replay and provenance contract).
func compareEvents(stored, replayed []Event) error {
	for i, want := range stored {
		if i >= len(replayed) {
			return fmt.Errorf("%w: event %d (%s) is not in the re-run, which stopped after %d events",
				ErrReplayDiverged, want.Seq, want.Kind, len(replayed))
		}

		// Compared as JSON, not structurally. The record is the source of
		// truth in its serialized form (docs/PRD.md FR8), and a stored
		// record has been through a round trip that a live one has not: an
		// omitempty slice comes back nil where the engine built it empty.
		// reflect.DeepEqual calls those two different and JSON calls them
		// the same, and JSON is the one the contract is written against.
		got := replayed[i]
		if wantJSON, gotJSON := describe(want), describe(got); wantJSON != gotJSON {
			return fmt.Errorf("%w: event %d: recorded %s, re-ran %s\n  recorded: %s\n  re-ran:   %s",
				ErrReplayDiverged, want.Seq, want.Kind, got.Kind, wantJSON, gotJSON)
		}
	}

	if len(replayed) > len(stored) {
		extra := replayed[len(stored)]

		return fmt.Errorf("%w: the re-run produced event %d (%s), which the record does not hold",
			ErrReplayDiverged, extra.Seq, extra.Kind)
	}

	return nil
}

// compareRecords compares the two records as JSON, the form the record is
// the source of truth in (docs/PRD.md FR8). Events are excluded because
// compareEvents has already reported them at a useful granularity; a whole
// event log in an error message is not a diagnostic.
func compareRecords(stored, replayed Character) error {
	stored.Events, replayed.Events = nil, nil

	// policy_version attests who decided, and on a re-run that is the
	// replay decider, so the regenerated record always reports "none".
	// Comparing it would fail every auto-generated record for saying
	// something true. This is the same reason it is not a provenance
	// check: replay reapplies recorded choices and never asks the policy.
	stored.PolicyVersion, replayed.PolicyVersion = "", ""

	want, err := json.Marshal(stored)
	if err != nil {
		return fmt.Errorf("marshalling the record: %w", err)
	}

	got, err := json.Marshal(replayed)
	if err != nil {
		return fmt.Errorf("marshalling the re-run: %w", err)
	}

	if !bytes.Equal(want, got) {
		return fmt.Errorf("%w: the events agree but the record does not: %s\n  recorded: %s\n  re-ran:   %s",
			ErrReplayDiverged, firstDifferingField(want, got), want, got)
	}

	return nil
}

// firstDifferingField names the top-level record field the two
// serializations disagree on, so a whole-record divergence points at
// something before it dumps both records. Names are compared in sorted
// order, so the answer is stable rather than map-iteration order. It
// degrades to a bare phrase rather than an error: it runs only on a
// divergence that is already being reported, and a failure to describe
// that divergence must not replace the report of it.
func firstDifferingField(want, got []byte) string {
	var wantFields, gotFields map[string]json.RawMessage
	if json.Unmarshal(want, &wantFields) != nil || json.Unmarshal(got, &gotFields) != nil {
		return "the records differ"
	}

	names := slices.Sorted(maps.Keys(wantFields))

	for name := range gotFields {
		if _, both := wantFields[name]; !both {
			names = append(names, name)
		}
	}

	slices.Sort(names)

	for _, name := range names {
		if !bytes.Equal(wantFields[name], gotFields[name]) {
			return name + " differs"
		}
	}

	return "the records differ"
}

// describe renders one event compactly for a divergence message.
func describe(event Event) string {
	out, err := json.Marshal(event)
	if err != nil {
		return fmt.Sprintf("%+v", event)
	}

	return string(out)
}

// recordedChoice pairs a recorded choice with the sequence number it was
// logged under, so a divergence can be reported against the record's own
// numbering rather than the replay's position.
type recordedChoice struct {
	seq   int
	event ChoiceEvent
}

// replayDecider answers each choice point with the recorded answer, in
// order. It is the "choice events are input" half of the replay contract
// (docs/PRD.md); the rest of the log is recomputed and compared.
type replayDecider struct {
	choices []recordedChoice
	next    int
	last    DeciderKind
}

// Choose returns the recorded index.
//
// It deliberately does not check that the engine is asking the recorded
// question. A recorded answer is an index, so the same number against a
// different option list means a different thing — POLICY.md's 0.10.0 entry
// records exactly that hazard — and an earlier draft compared the prompt
// and options here. But the engine writes the presented prompt and options
// into the choice event it logs (see choose), so a record whose options no
// longer match produces a choice event that no longer matches, and
// compareEvents reports it against the same sequence number. The pre-check
// could not be made to fail any test the event comparison did not already
// fail, so it was removed rather than kept as untested redundancy.
//
// The range check stays because it is not redundant: an index past the
// engine's option list would otherwise come back as errBadChoice, which
// says the decider answered wrongly when what happened is that the record
// and the engine disagree.
func (d *replayDecider) Choose(c Choice) (int, error) {
	if d.next >= len(d.choices) {
		return 0, fmt.Errorf("%w: after event %d the engine asked %q, past the %d choices the record holds",
			ErrReplayDiverged, d.lastSeq(), c.ID, len(d.choices))
	}

	recorded := d.choices[d.next]
	d.next++
	d.last = recorded.event.Decider

	if recorded.event.Chosen < 0 || recorded.event.Chosen >= len(c.Options) {
		return 0, fmt.Errorf("%w: event %d: recorded the answer %d, outside the %d options",
			ErrReplayDiverged, recorded.seq, recorded.event.Chosen, len(c.Options))
	}

	return recorded.event.Chosen, nil
}

// Kind reports who decided the choice just answered, so the re-run's
// choice events attest the original decider rather than the replay. Choose
// runs first at every call site (see choose), so the recorded kind is
// already in hand.
//
// This makes attribution unverifiable, and deliberately so: the replay
// decider is not the original, so the only kind it can report is the
// recorded one, which then matches itself in compareEvents. A record whose
// decider fields (or policy_version, excluded for the same reason) were
// altered replays clean. Replay attests that the recorded choices rebuild
// the recorded character, not that the named decider would make them.
func (d *replayDecider) Kind() DeciderKind {
	return d.last
}

// lastSeq is the record's sequence number for the choice last consumed, or
// 0 before any: the contract reports a divergence against the record's own
// numbering ("reporting the diverging event's sequence number",
// docs/PRD.md), and a re-run that outran the record diverges somewhere
// after the last answer it was given.
func (d *replayDecider) lastSeq() int {
	if d.next == 0 {
		return 0
	}

	return d.choices[d.next-1].seq
}
